#!/bin/bash
#PBS -m abe
#PBS -l nodes=1:ppn=20,vmem=40gb,walltime=4:00:00
#PBS -N WGtdna
#PBS -j oe

## Aim: To check for the presence and location of the T-DNA sequences in the transgenic plant genomes.
# Author: Chun-Yuan Huang, Ph.D.
# Last Update: 3/01/2016

## Prerequisite files
# Ti Plasmid. TALEN.fa is the TALEN vector sequence that contains pTALEN-Os11N3-LR and pTALEN-8N3-LR for use in the TALEN mutagenesis.
# The SOAPdenovo2-assembled sample contigs ${i}-soap.contig and its indexed blastn database DB_${i}_contig.

cd $PBS_O_WORKDIR
source ./0SOURCE
cd ${run_DIR}
mkdir -p tdna
cd ${run_DIR}/tdna
QUERY=TALEN.fa
QUERYNAME=TALEN

##---------------------------------
## To find left-over T-DNA seq in the sample contigs
\rm blastn.YB-on-TALEN_TDNA.table
for i in ${SAMPLE}
do
blastn -db ${prereq_DIR}/DB_${i}_contig -query ${prereq_DIR}/${QUERY} -evalue ${EVALUE} > blastn.${QUERYNAME}-on-${i}.aln
blastn -db ${prereq_DIR}/DB_${i}_contig -query ${prereq_DIR}/${QUERY} -evalue ${EVALUE} -outfmt 6 > blastn.${QUERYNAME}-on-${i}.table
cat blastn.${QUERYNAME}-on-${i}.table >> blastn.YB-on-TALEN_TDNA.table
done
echo "qseqid  sseqid  pident  length  mismatch gapopen qstart qend sstart send  evalue  bitscore" |\
cat - blastn.YB-on-TALEN_TDNA.table > tmp && \mv tmp blastn.YB-on-TALEN_TDNA.table

\cp blastn.YB-on-TALEN_TDNA.table ${data_DIR}

