#!/bin/bash
#PBS -m abe
#PBS -l nodes=1:ppn=20,vmem=20gb,walltime=1:00:00
#PBS -N x5-DFPtree
#PBS -j oe

module add python

cd $PBS_O_WORKDIR
source ./0SOURCE
cd ${run_DIR}/iloci

echo "## Aim: To reveal phylogenic relationship among sample cultivars based on their Deletion Fingerprints (DFP) [1].
# Proposition: Rice cultivars with high proportion of shared deletion sites [2] have similar DFP, and are close to each other in phylogeny.
# Input: Seq.t_sum_Lg${GAP_MINSIZE_FP}.giloci from x4-DFP
# Method: Compute the distance matrix of shared deletion sites among sample cultivars, then construct a phylogenic tree.
# Output: phylogenic tree of sample cultivars.

# [1] Deletion Fingerprints (DFP): Set of deletions of the assembled contigs when compared to the reference genome. The deletions are
# further restricted to the genic region (giloci) with the minimal length GAP_MINSIZE_FP in order to reduce the noise
# from sequencing/assembly errors on repetitive and low complexity regions.
# [2] Shared deletion site: the deletion site has EXACT start and end position in the reference for the compared samples.

##------------------
# The following cultivars are samples for baseline construction for intra- and inter- varietal groups.
# BINIAPAN: CX113 Biniapan Tropical japonica
# KOTOOURA: IRIS 313-10712 KOTO OURA S 5::IRGC 15155-1 KOTO OURA S 5 Tropical japonica
# PATIEROUGE: IRIS 313-11540 PATIE ROUGE::IRGC 57686-1 PATIE ROUGE 12.2 Tropical japonica
# MANYALOJOPOIHUN: IRIS 313-11658 MANYALOJOPOIHUN::IRGC 63350-1 MANYALOJOPOIHUN 15.5 Tropical japonica
# A2_257: IRIS 313-11755 A 2-257::IRGC 68342-1 A 2-257 Tropical japonica

# GINMASARI: IRIS 313-10430 GINMASARI::IRGC 242-1 GINMASARI Temperate japonica
# KOTOBUKIMOCHI: IRIS 313-9002 KOTOBUKI MOCHI::IRGC 2545-1-1 KOTOBUKI MOCHI 8.5 Temperate japonica
# NIPPONBARE: CX140 Nipponbare Temperate japonica
# SACHIKAZE: IRIS 313-10642 SACHIKAZE::IRGC 10891-1 SACHIKAZE Temperate japonica

# OSATIVA: IRIS 313-9882 O SATIVA::IRGC 17083-1-1 UNNAMED 10.3 Indica
# CHINGCHUNG: IRIS 313-11693 CHING CH'UNG::IRGC 65002-1 CHING-CH'UNG 17.3 Indica
# NIAOYAO: IRIS 313-8743 NIAO YAO::IRGC 5496-1-1 NIAO YAO 9.4 Indica
# CHINGLIU: IRIS 313-11694 CHING LIU::IRGC 65018-1 CHING-LIU 12.1 Indica

# ARC11571: IRIS 313-10868 ARC 11571::IRGC 21487-1 ARC 11571 Basmati/sadri
# JC_157: IRIS 313-9629 JC 157::IRGC 9074-1-1 JC157 Aus/boro
# KEYANUNIA: IRIS 313-11362 KEYA NUNIA::IRGC 46117-1 KEYA NUNIA Basmati/sadri
# MADHUWAKARIA: IRIS 313-10732 MADHUWA KARIA::IRGC 16138-1 MADHUWA KARIA Basmati/sadri
# CR441: IRIS 313-11356 CR 44-1::IRGC 45397-1 CR44-1 Basmati/sadri
##-------------------
" > ${SAMPLENAME}_phylotree.result


# Setup for comparison
# SAMPLE="YB1 YB2 YB3 YB4 YB5 YB6 YB7 YB8"
# SAMPLE="A2_257 BINIAPAN CHINGLIU GINMASARI KEYANUNIA KOTOOURA MANYALOJOPOIHUN NIPPONBARE PATIEROUGE ARC11571 CHINGCHUNG CR441 JC_157 KOTOBUKIMOC\
HI MADHUWAKARIA NIAOYAO OSATIVA SACHIKAZE"
# SAMPLE="GINMASARI KOTOBUKIMOCHI NIPPONBARE SACHIKAZE BINIAPAN KOTOOURA PATIEROUGE MANYALOJOPOIHUN A2_257 ARC11571 JC_157 KEYANUNIA MADHUWAKARIA \
CR441 OSATIVA CHINGCHUNG NIAOYAO CHINGLIU"
# SAMPLENAME=VarGrp
# SAMPLENUM=18

#1 Input is file Seq.t_sum_Lg${GAP_MINSIZE_FP}.giloci with the content such as:
# Tname tGapStart tGapSize tGapEnd Samples iloci
# OsjChr1 10008136 275 10008411 CHINGLIU;KEYANUNIA;ARC11571;CHINGCHUNG;CR441;JC_157;MADHUWAKARIA;NIAOYAO;OSATIVA; locus1510
# Transform the above table into a matrix ush as:
# Tname tGapStart tGapSize tGapEnd A2_257;BINIAPAN;CHINGLIU;GINMASARI;KEYANUNIA;KOTOOURA;MANYALOJOPOIHUN;NIPPONBARE;PATIEROUGE;ARC11571;CHINGCHUNG\
;
# OsjChr1 10008136 275 10008411 0;0;1;0;1;0;0;0;0;1;1;

\rm Seq.t_sum_Lg${GAP_MINSIZE_FP}.matrix
len=`awk 'END { print NR }' Seq.t_sum_Lg${GAP_MINSIZE_FP}.giloci`
for ((k=1; k<=$len; k++))
do
head -$k Seq.t_sum_Lg${GAP_MINSIZE_FP}.giloci | tail -1 > rec
Tname=`cut -d " " -f1 rec`
tGapStart=`cut -d " " -f2 rec`
tGapSize=`cut -d " " -f3 rec`
tGapEnd=`cut -d " " -f4 rec`
Samples=`cut -d " " -f5 rec | tr ";" " "`
iloci=`cut -d " " -f6 rec`

\rm rec.SAMPLE
for i in ${SAMPLE}
do
if [[ $Samples =~ $i  ]]; then
    echo "1" >> rec.SAMPLE
else
    echo "0" >> rec.SAMPLE
fi
done
awk 1 ORS=';' rec.SAMPLE > rec_SAMPLE
recSAMPLE=`cat rec_SAMPLE | tr ";" " "`
echo "${Tname}_${tGapStart}_${tGapSize}_${tGapEnd} ${recSAMPLE}" >> Seq.t_sum_Lg${GAP_MINSIZE_FP}.matrix
done


recSAMPLEname=`echo $SAMPLE`
echo "Tname_tGapStart_tGapSize_tGapEnd $recSAMPLEname" | cat - Seq.t_sum_Lg${GAP_MINSIZE_FP}.matrix > Seq.t_sum_Lg${GAP_MINSIZE_FP}.Matrix


##----------------------
#2 Python scriptto take the Seq.t_sum_Lg${GAP_MINSIZE_FP}.matrix and compute the distance matrix






##----------------------
## Cleanup and report
cd ${run_DIR}/iloci
\rm -r delrec*

cd ${data_DIR}
\cp -r ${run_DIR}/iloci/Seq.t_sum_Lg${GAP_MINSIZE_FP}.* .
rename Seq.t ${SAMPLENAME}_SeqDel Seq.t*








