#!/bin/bash
#PBS -m abe
#PBS -l nodes=1:ppn=20,vmem=20gb,walltime=1:00:00
#PBS -N x5-PhyloTree
#PBS -j oe

cd $PBS_O_WORKDIR
source ./0SOURCE
cd ${data_DIR}

echo "## Aim: To reveal phylogenic relationship among sample cultivars based on their Deletion Fingerprints (DFP) [1].
# Proposition: Rice cultivars with high proportion of shared deletion sites [2] have similar DFP, and are close to each other in phylogeny.
# Input: Seq.t_sum_Lg${GAP_MINSIZE_FP}.giloci from x4-DFP
# Method: Compute the proportion of shared deletion sites among sample cultivars, then construct a phylogenic tree.
# Output: phylogenic tree of sample cultivars.

# [1] Deletion Fingerprints (DFP): Set of deletions of the assembled contigs when compared to the reference genome. The deletions are
# further restricted to the genic region (giloci) with the minimal length GAP_MINSIZE_FP in order to reduce the noise
# from sequencing/assembly errors on repetitive and low complexity regions.
# [2] Shared deletion site: the deletion site has EXACT start and end position in the reference for the compared samples.

##------------------
# The following cultivars are samples for baseline construction for intra- and inter- varietal groups.
# BINIAPAN: CX113 Biniapan Tropical japonica
# KOTOOURA: IRIS 313-10712 KOTO OURA S 5::IRGC 15155-1 KOTO OURA S 5 Tropical japonica
# PATIEROUGE: IRIS 313-11540 PATIE ROUGE::IRGC 57686-1 PATIE ROUGE 12.2 Tropical japonica
# MANYALOJOPOIHUN: IRIS 313-11658 MANYALOJOPOIHUN::IRGC 63350-1 MANYALOJOPOIHUN 15.5 Tropical japonica
# A2_257: IRIS 313-11755 A 2-257::IRGC 68342-1 A 2-257 Tropical japonica

# GINMASARI: IRIS 313-10430 GINMASARI::IRGC 242-1 GINMASARI Temperate japonica
# KOTOBUKIMOCHI: IRIS 313-9002 KOTOBUKI MOCHI::IRGC 2545-1-1 KOTOBUKI MOCHI 8.5 Temperate japonica
# NIPPONBARE: CX140 Nipponbare Temperate japonica
# SACHIKAZE: IRIS 313-10642 SACHIKAZE::IRGC 10891-1 SACHIKAZE Temperate japonica

# OSATIVA: IRIS 313-9882 O SATIVA::IRGC 17083-1-1 UNNAMED 10.3 Indica
# CHINGCHUNG: IRIS 313-11693 CHING CH'UNG::IRGC 65002-1 CHING-CH'UNG 17.3 Indica
# NIAOYAO: IRIS 313-8743 NIAO YAO::IRGC 5496-1-1 NIAO YAO 9.4 Indica
# CHINGLIU: IRIS 313-11694 CHING LIU::IRGC 65018-1 CHING-LIU 12.1 Indica

# ARC11571: IRIS 313-10868 ARC 11571::IRGC 21487-1 ARC 11571 Basmati/sadri
# JC_157: IRIS 313-9629 JC 157::IRGC 9074-1-1 JC157 Aus/boro
# KEYANUNIA: IRIS 313-11362 KEYA NUNIA::IRGC 46117-1 KEYA NUNIA Basmati/sadri
# MADHUWAKARIA: IRIS 313-10732 MADHUWA KARIA::IRGC 16138-1 MADHUWA KARIA Basmati/sadri
# CR441: IRIS 313-11356 CR 44-1::IRGC 45397-1 CR44-1 Basmati/sadri
##-------------------
" > ${SAMPLENAME}_phylotree.result

# Setup for comparison
# SAMPLE="YB1 YB2 YB3 YB4 YB5 YB6 YB7 YB8"
SAMPLE="A2_257 BINIAPAN CHINGLIU GINMASARI KEYANUNIA KOTOOURA MANYALOJOPOIHUN NIPPONBARE PATIEROUGE ARC11571 CHINGCHUNG CR441 JC_157 KOTOBUKIMOCHI MADHU\
WAKARIA NIAOYAO OSATIVA SACHIKAZE"
SAMPLENAME=VarGrp
SAMPLENUM=18


\rm -f FP*
for i in ${SAMPLE}
do
egrep "(${QUERY}|$i)" SeqDel_sum_Lg${GAP_MINSIZE_FP}.table > FP_union_${QUERYNAME}_${i}
egrep "${QUERY}" SeqDel_sum_Lg${GAP_MINSIZE_FP}.table | egrep "$i" > FP_intcpt_${QUERYNAME}_${i}
done


target=`wc -l SeqDel_sum_Lg${GAP_MINSIZE_FP}.table | cut -d" " -f1`
echo "Total deletion sites in SeqDel_sum_Lg${GAP_MINSIZE_FP}.table are $target" >> stat.result

query=`grep "NIPPONBARE" SeqDel_sum_Lg${GAP_MINSIZE_FP}.table | wc -l | cut -d" " -f1`
echo "Total deletion sites from ${QUERYNAME} are $query" >> stat.result

# grep union of all samples
egrep "(YB1|YB2|YB3|YB4|YB5|YB6|YB7|YB8)" SeqDel_sum_Lg${GAP_MINSIZE_FP}.table > FP_union_${SAMPLENAME}
samples=`wc -l FP_union_${SAMPLENAME} | cut -d" " -f1`
echo "Total deletion sites from ${SAMPLENAME} samples are ${samples}" >> stat.result

# grep intercept of all samples
egrep "${QUERY}" SeqDel_sum_Lg${GAP_MINSIZE_FP}.table | egrep "YB1" | egrep "YB2" | \
egrep "YB3" | egrep "YB4" | egrep "YB5" | egrep "YB6" | \
egrep "YB7" | egrep "YB8" > FP_intcpt_${QUERYNAME}_${SAMPLENAME}
query_samples=`wc -l FP_intcpt_${QUERYNAME}_${SAMPLENAME} | cut -d" " -f1`
echo "Total deletion sites that are shared among ${QUERYNAME} and ${SAMPLENAME} samples are ${query_samples}" >> ${SAMPLENAME}_phylotree.result
echo "" >> stat.result


for i in ${SAMPLE}
do
echo "##" >> stat.result
sample=`grep "$i" SeqDel_sum_Lg${GAP_MINSIZE_FP}.table | wc -l | cut -d" " -f1`
echo "Total deletion sites from sample ${i} are $sample" >> stat.result
query_sample=`wc -l FP_intcpt_${QUERYNAME}_${i}  | cut -d" " -f1`
echo "Total deletion sites from sample ${i} that are also shared with ${QUERYNAME} are ${query_sample}" >> stat.result
perc_sample=`awk "BEGIN { print ${query_sample}/${sample}*100 }"`
echo "Percentage of deletion sites that are shared by ${i} and ${QUERYNAME} as compared to deletion sites of sample ${i} is ${perc_sample}%" >> stat.res\
ult
done

echo "

#-------------------------
## Conclusion:
#1. The NIPPONBARE (CX140) from 3kRGP has already accumulated 694 deletions as compared to the reference of its own.
#2. Using deletion sites as fingerprinting marker, NIPPONBARE shared similar number of deletions (187-212, average 201)
#   with individual sample. Among them, 80 deletions sites are shared for NIPPONBARE and all YB1-YB8.
#3. There are 2.86 folds more deletions in YB2-YB8 than in YB1, as compared to the reference Nipponbare.
#4. YB1 has higher percentage (10%) of Nipponbare-shared deletion sites than other YB samples (~3.8%).
#5. It is likely that YB1 is a cultivar closer to NIPPONBARE than YB2-YB8 are to NIPPONBARE, based on the observations #3 and #4.
#6. The Indel fingerprinting result is consistent with the SNP fingerprinting result, which shows strong evidence that
#   NIPPONBARE is the closest relative among all 3kRGP to YB1.

" >> ${SAMPLENAME}_phylotree.result

