#!/bin/bash
source ./0SOURCE
cd ${WORK_DIR}

## Clean up the qsub error message files
mv *.o* ${scratch_DIR}

## Clean up the blat intermediate files
cd ${run_DIR}
\rm -r *.Reps.psr
\rm -r rec*

## Clean up deletion table *.sample, *.fasta and *.fa files
for indel in t_onQ t_sum
do
cd ${run_DIR}/${indel}
\rm -r rec*
mkdir -p ${scratch_DIR}/${indel}/file_sample
mv *.sample ${scratch_DIR}/${indel}/file_sample

mkdir -p ${scratch_DIR}/${indel}/file_contig
mv *.fa ${scratch_DIR}/${indel}/file_contig

mkdir -p ${scratch_DIR}/${indel}/file_gap
mv *_GAP_*.fasta ${scratch_DIR}/${indel}/file_gap
done

## clean up ptalen intermediate files
cd ${run_DIR}/ptalen
\rm -r Trec*
mkdir -p ${scratch_DIR}/ptalen/deletion
mv Prec* ${scratch_DIR}/ptalen/deletion

