#!/bin/bash
source ./0SOURCE
cd ${WORK_DIR}

## Clean up the qsub error message files
mv *.o* scratch/

## Clean up the blat intermediate files
cd ${run_DIR}
\rm -r *.Reps.psr
\rm -r rec*

## clean up deletion table *.sample, *.fasta and *.fa files
for indel in t_onQ t_sum
do
cd ${run_DIR}/${indel}
\rm -r rec*
mkdir -p ${run_DIR}/${indel}/file_sample
mv *.sample ${run_DIR}/${indel}/file_sample

mkdir -p ${run_DIR}/${indel}/file_contig
mv *.fa ${run_DIR}/${indel}/file_contig

mkdir -p ${run_DIR}/${indel}/file_gap
mv *_GAP_*.fasta ${run_DIR}/${indel}/file_gap

## clean up ptalen intermediate files
cd ${run_DIR}/ptalen
mkdir -p ${run_DIR}/ptalen/deletion
mv Prec* ${run_DIR}/ptalen/deletion

done
